const cars = [
    {
        id: 1,
        name: "Bmw",
        wheelDrive: "Rwd",
        color: "red",
        new: true,
        year: 2019,
    },
    {
        id: 2,
        name: "Mercedes",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2018,
    },
    {
        id: 3,
        name: "Tesla",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2019,
    },
    {
        id: 4,
        name: "Tesla",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2019,
    },
    {
        id: 5,
        name: "Toyota",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2019,
    },
    {
        id: 6,
        name: "Volvo",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },
    {
        id: 7,
        name: "Lexsus",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },
    {
        id: 8,
        name: "Bmw",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2019,
    },
    {
        id: 9,
        name: "Nisaan",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2019,
    },
    {
        id: 10,
        name: "Mercedes",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },
    {
        id: 11,
        name: "Bentley",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },
    {
        id: 12,
        name: "Dodge",
        wheelDrive: "Awd",
        color: "silver",
        new: false,
        year: 2019,
    },
    {
        id: 13,
        name: "Rolls Royce",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },
    {
        id: 14,
        name: "Audi",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },
    {
        id: 15,
        name: "Ferrari",
        wheelDrive: "Awd",
        color: "silver",
        new: true,
        year: 2019,
    },


]