const products = [
    { title: 'Cheese', price: 15.0 },
    { title: 'Milk', price: 8.99 },
    { title: 'Bread', price: 22.0 },
    { title: 'RedBull', price: 2.4 },
    { title: 'Chicken', price: 5 },
    { title: 'Soda', price: 5 },
    { title: 'Soap', price: 5 },
    { title: 'Coffee', price: 5 },
    { title: 'Tea', price: 5 },
    { title: 'Glass', price: 5 },
    { title: 'Glass Cleaner', price: 5 },
    { title: 'Onion', price: 5 },
    { title: 'Tomato', price: 5 },
    { title: 'Bread Sticks', price: 5 },
    { title: 'Chilli', price: 5 },
    { title: 'Potato', price: 5 },
    { title: 'Spinat', price: 5 },
    { title: 'Sparkling Water', price: 5 },
    { title: 'Tonic water', price: 5 },
    { title: 'Cola', price: 5 },
    { title: 'Pizza', price: 5 },
    { title: 'Brown Cheese', price: 5 },
    { title: 'Gum', price: 5 },
    { title: 'Vitamin Pills', price: 5 },
    { title: 'Cookies', price: 5 },
    { title: 'Mayo', price: 5 },
    { title: 'Beer', price: 5 },
    { title: 'Cider', price: 5 },
    { title: 'Cloth Cleaner', price: 5 },
    { title: 'Orange', price: 5 },
];